[workspace]
channels = ["conda-forge", "bioconda"]
name = "bifx_live_snakemake_2026"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake-minimal = ">=9.7.1"
jinja2 = "*"
matplotlib = "*"
graphviz = "*"
bcftools = ">=1.19"
samtools = ">=1.19"
bwa = "~=0.7.17"
pygments = "*"
pysam = "0.22.*"
